export default {
  name: 'runPage',
  title: 'Run Page',
  type: 'document',
  preview: {
    select: {
      title: 'eventTitle',
      subtitle: 'displayDate',
    },
  },
  fields: [
    {name: 'eventTitle', title: 'Event Title', type: 'string'},
    {name: 'eventSubtitle', title: 'Event Subtitle', type: 'string'},
    {name: 'date', title: 'Date', type: 'string'},
    {name: 'displayDate', title: 'Display Date', type: 'string'},
    {name: 'dateFormatted', title: 'Date Formatted', type: 'string'},
    {name: 'time', title: 'Time', type: 'string'},
    {name: 'location', title: 'Location', type: 'string'},
    {name: 'locationShort', title: 'Location Short', type: 'string'},
    {name: 'badgeText', title: 'Badge Text', type: 'string'},
    {name: 'heroTitle', title: 'Hero Title', type: 'string'},
    {name: 'heroHighlight', title: 'Hero Highlight', type: 'string'},
    {name: 'heroSubtitle', title: 'Hero Subtitle', type: 'string'},
    {name: 'heroDescription', title: 'Hero Description', type: 'text'},
    {name: 'heroImage', title: 'Hero Image', type: 'image', options: {hotspot: true}},
    {name: 'eventDetailsTitle', title: 'Event Details Title', type: 'string'},
    {
      name: 'eventDetailsDescription',
      title: 'Event Details Description',
      type: 'array',
      of: [{type: 'text'}],
    },
    {name: 'hashtags', title: 'Hashtags', type: 'string'},
    {
      name: 'eventHighlights',
      title: 'Event Highlights',
      type: 'array',
      of: [{type: 'object', fields: [
        {name: 'title', title: 'Title', type: 'string'},
        {name: 'content', title: 'Content', type: 'array', of: [{type: 'text'}]},
      ]}],
    },
    {name: 'impactStatsTitle', title: 'Impact Stats Title', type: 'string'},
    {name: 'impactStatsSubtitle', title: 'Impact Stats Subtitle', type: 'string'},
    {
      name: 'years',
      title: 'Years',
      type: 'array',
      of: [{type: 'object', fields: [
        {name: 'year', title: 'Year', type: 'string'},
        {name: 'amount', title: 'Amount', type: 'string'},
        {name: 'isGoal', title: 'Is Goal', type: 'boolean'},
      ]}],
    },
    {name: 'goalDescription', title: 'Goal Description', type: 'text'},
    {name: 'getInvolvedTitle', title: 'Get Involved Title', type: 'string'},
    {name: 'getInvolvedDescription', title: 'Get Involved Description', type: 'text'},
    {
      name: 'cards',
      title: 'Cards',
      type: 'array',
      of: [{type: 'object', fields: [
        {name: 'title', title: 'Title', type: 'string'},
        {name: 'description', title: 'Description', type: 'text'},
        {name: 'buttonText', title: 'Button Text', type: 'string'},
        {name: 'buttonUrl', title: 'Button URL', type: 'url'},
      ]}],
    },
    {name: 'aboutRunTitle', title: 'About Run Title', type: 'string'},
    {
      name: 'aboutRunDescription',
      title: 'About Run Description',
      type: 'array',
      of: [{type: 'text'}],
    },
    {name: 'runHashtags', title: 'Run Hashtags', type: 'string'},
    {name: 'registrationUrl', title: 'Registration URL', type: 'url'},
  ],
}